name: Release

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-docker:
    uses: ./.github/workflows/docker-publish.yml
    secrets: inherit
